### ISSUE TITLE
KNGLauncher Checklist

### ISSUE THREAD

**Issue by KnightryryV2** [KnightryryV2/KNGLauncher-but-bad#1]
- [x] Upload All needed files
- [ ] Make UI Nicer
- [ ] Make README.md with build instructions.
- [ ] Check that code works
